// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/internal.protocol.proto

#ifndef PROTOBUF_proto_2finternal_2eprotocol_2eproto__INCLUDED
#define PROTOBUF_proto_2finternal_2eprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace internal {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

class PingReq;
class PongRsp;
class LoginDBAgentReq;
class LoginDBAgentRsp;
class QueryDBAgentReq;
class QueryDBAgentRsp;
class DBErrorRsp;
class DBAgentErrorRsp;
class RouterErrorRsp;
class LoginRouterReq;
class LoginRouterRsp;
class ForwardMessageReq;
class ForwardMessageRsp;
class BroadcastMessageReq;
class BroadcastMessageRsp;

enum QueryDBAgentReq_ActoinType {
  QueryDBAgentReq_ActoinType_kSelect = 1,
  QueryDBAgentReq_ActoinType_kInsert = 2,
  QueryDBAgentReq_ActoinType_kUpdate = 3,
  QueryDBAgentReq_ActoinType_kDelete = 4
};
bool QueryDBAgentReq_ActoinType_IsValid(int value);
const QueryDBAgentReq_ActoinType QueryDBAgentReq_ActoinType_ActoinType_MIN = QueryDBAgentReq_ActoinType_kSelect;
const QueryDBAgentReq_ActoinType QueryDBAgentReq_ActoinType_ActoinType_MAX = QueryDBAgentReq_ActoinType_kDelete;
const int QueryDBAgentReq_ActoinType_ActoinType_ARRAYSIZE = QueryDBAgentReq_ActoinType_ActoinType_MAX + 1;

const ::google::protobuf::EnumDescriptor* QueryDBAgentReq_ActoinType_descriptor();
inline const ::std::string& QueryDBAgentReq_ActoinType_Name(QueryDBAgentReq_ActoinType value) {
  return ::google::protobuf::internal::NameOfEnum(
    QueryDBAgentReq_ActoinType_descriptor(), value);
}
inline bool QueryDBAgentReq_ActoinType_Parse(
    const ::std::string& name, QueryDBAgentReq_ActoinType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<QueryDBAgentReq_ActoinType>(
    QueryDBAgentReq_ActoinType_descriptor(), name, value);
}
enum QueryDBAgentReq_DatabaseType {
  QueryDBAgentReq_DatabaseType_kRedis = 1,
  QueryDBAgentReq_DatabaseType_kMySQL = 2
};
bool QueryDBAgentReq_DatabaseType_IsValid(int value);
const QueryDBAgentReq_DatabaseType QueryDBAgentReq_DatabaseType_DatabaseType_MIN = QueryDBAgentReq_DatabaseType_kRedis;
const QueryDBAgentReq_DatabaseType QueryDBAgentReq_DatabaseType_DatabaseType_MAX = QueryDBAgentReq_DatabaseType_kMySQL;
const int QueryDBAgentReq_DatabaseType_DatabaseType_ARRAYSIZE = QueryDBAgentReq_DatabaseType_DatabaseType_MAX + 1;

const ::google::protobuf::EnumDescriptor* QueryDBAgentReq_DatabaseType_descriptor();
inline const ::std::string& QueryDBAgentReq_DatabaseType_Name(QueryDBAgentReq_DatabaseType value) {
  return ::google::protobuf::internal::NameOfEnum(
    QueryDBAgentReq_DatabaseType_descriptor(), value);
}
inline bool QueryDBAgentReq_DatabaseType_Parse(
    const ::std::string& name, QueryDBAgentReq_DatabaseType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<QueryDBAgentReq_DatabaseType>(
    QueryDBAgentReq_DatabaseType_descriptor(), name, value);
}
enum ErrorCode {
  kNotLoggedIn = 1,
  kDisconnect = 2,
  kNotConnected = 3,
  kInvalidProtocol = 4,
  kInvalidOperation = 5,
  kNotFoundDatabase = 6,
  kResourceInsufficiency = 7,
  kDestinationUnreachable = 8,
  kInvalidNodeType = 9,
  kRepeatLogin = 10,
  kInvalidDataPacket = 11
};
bool ErrorCode_IsValid(int value);
const ErrorCode ErrorCode_MIN = kNotLoggedIn;
const ErrorCode ErrorCode_MAX = kInvalidDataPacket;
const int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor();
inline const ::std::string& ErrorCode_Name(ErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ErrorCode_descriptor(), value);
}
inline bool ErrorCode_Parse(
    const ::std::string& name, ErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
enum NodeType {
  kLicenceServer = 1,
  kLinkerServer = 2,
  kMainLogicSever = 3
};
bool NodeType_IsValid(int value);
const NodeType NodeType_MIN = kLicenceServer;
const NodeType NodeType_MAX = kMainLogicSever;
const int NodeType_ARRAYSIZE = NodeType_MAX + 1;

const ::google::protobuf::EnumDescriptor* NodeType_descriptor();
inline const ::std::string& NodeType_Name(NodeType value) {
  return ::google::protobuf::internal::NameOfEnum(
    NodeType_descriptor(), value);
}
inline bool NodeType_Parse(
    const ::std::string& name, NodeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NodeType>(
    NodeType_descriptor(), name, value);
}
// ===================================================================

class PingReq : public ::google::protobuf::Message {
 public:
  PingReq();
  virtual ~PingReq();

  PingReq(const PingReq& from);

  inline PingReq& operator=(const PingReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PingReq& default_instance();

  void Swap(PingReq* other);

  // implements Message ----------------------------------------------

  PingReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PingReq& from);
  void MergeFrom(const PingReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:internal.PingReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static PingReq* default_instance_;
};
// -------------------------------------------------------------------

class PongRsp : public ::google::protobuf::Message {
 public:
  PongRsp();
  virtual ~PongRsp();

  PongRsp(const PongRsp& from);

  inline PongRsp& operator=(const PongRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PongRsp& default_instance();

  void Swap(PongRsp* other);

  // implements Message ----------------------------------------------

  PongRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PongRsp& from);
  void MergeFrom(const PongRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:internal.PongRsp)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static PongRsp* default_instance_;
};
// -------------------------------------------------------------------

class LoginDBAgentReq : public ::google::protobuf::Message {
 public:
  LoginDBAgentReq();
  virtual ~LoginDBAgentReq();

  LoginDBAgentReq(const LoginDBAgentReq& from);

  inline LoginDBAgentReq& operator=(const LoginDBAgentReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginDBAgentReq& default_instance();

  void Swap(LoginDBAgentReq* other);

  // implements Message ----------------------------------------------

  LoginDBAgentReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginDBAgentReq& from);
  void MergeFrom(const LoginDBAgentReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:internal.LoginDBAgentReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static LoginDBAgentReq* default_instance_;
};
// -------------------------------------------------------------------

class LoginDBAgentRsp : public ::google::protobuf::Message {
 public:
  LoginDBAgentRsp();
  virtual ~LoginDBAgentRsp();

  LoginDBAgentRsp(const LoginDBAgentRsp& from);

  inline LoginDBAgentRsp& operator=(const LoginDBAgentRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginDBAgentRsp& default_instance();

  void Swap(LoginDBAgentRsp* other);

  // implements Message ----------------------------------------------

  LoginDBAgentRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginDBAgentRsp& from);
  void MergeFrom(const LoginDBAgentRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 heartbeat_interval = 1;
  inline bool has_heartbeat_interval() const;
  inline void clear_heartbeat_interval();
  static const int kHeartbeatIntervalFieldNumber = 1;
  inline ::google::protobuf::uint32 heartbeat_interval() const;
  inline void set_heartbeat_interval(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:internal.LoginDBAgentRsp)
 private:
  inline void set_has_heartbeat_interval();
  inline void clear_has_heartbeat_interval();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 heartbeat_interval_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static LoginDBAgentRsp* default_instance_;
};
// -------------------------------------------------------------------

class QueryDBAgentReq : public ::google::protobuf::Message {
 public:
  QueryDBAgentReq();
  virtual ~QueryDBAgentReq();

  QueryDBAgentReq(const QueryDBAgentReq& from);

  inline QueryDBAgentReq& operator=(const QueryDBAgentReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QueryDBAgentReq& default_instance();

  void Swap(QueryDBAgentReq* other);

  // implements Message ----------------------------------------------

  QueryDBAgentReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QueryDBAgentReq& from);
  void MergeFrom(const QueryDBAgentReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef QueryDBAgentReq_ActoinType ActoinType;
  static const ActoinType kSelect = QueryDBAgentReq_ActoinType_kSelect;
  static const ActoinType kInsert = QueryDBAgentReq_ActoinType_kInsert;
  static const ActoinType kUpdate = QueryDBAgentReq_ActoinType_kUpdate;
  static const ActoinType kDelete = QueryDBAgentReq_ActoinType_kDelete;
  static inline bool ActoinType_IsValid(int value) {
    return QueryDBAgentReq_ActoinType_IsValid(value);
  }
  static const ActoinType ActoinType_MIN =
    QueryDBAgentReq_ActoinType_ActoinType_MIN;
  static const ActoinType ActoinType_MAX =
    QueryDBAgentReq_ActoinType_ActoinType_MAX;
  static const int ActoinType_ARRAYSIZE =
    QueryDBAgentReq_ActoinType_ActoinType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ActoinType_descriptor() {
    return QueryDBAgentReq_ActoinType_descriptor();
  }
  static inline const ::std::string& ActoinType_Name(ActoinType value) {
    return QueryDBAgentReq_ActoinType_Name(value);
  }
  static inline bool ActoinType_Parse(const ::std::string& name,
      ActoinType* value) {
    return QueryDBAgentReq_ActoinType_Parse(name, value);
  }

  typedef QueryDBAgentReq_DatabaseType DatabaseType;
  static const DatabaseType kRedis = QueryDBAgentReq_DatabaseType_kRedis;
  static const DatabaseType kMySQL = QueryDBAgentReq_DatabaseType_kMySQL;
  static inline bool DatabaseType_IsValid(int value) {
    return QueryDBAgentReq_DatabaseType_IsValid(value);
  }
  static const DatabaseType DatabaseType_MIN =
    QueryDBAgentReq_DatabaseType_DatabaseType_MIN;
  static const DatabaseType DatabaseType_MAX =
    QueryDBAgentReq_DatabaseType_DatabaseType_MAX;
  static const int DatabaseType_ARRAYSIZE =
    QueryDBAgentReq_DatabaseType_DatabaseType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  DatabaseType_descriptor() {
    return QueryDBAgentReq_DatabaseType_descriptor();
  }
  static inline const ::std::string& DatabaseType_Name(DatabaseType value) {
    return QueryDBAgentReq_DatabaseType_Name(value);
  }
  static inline bool DatabaseType_Parse(const ::std::string& name,
      DatabaseType* value) {
    return QueryDBAgentReq_DatabaseType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required uint32 sequence = 1;
  inline bool has_sequence() const;
  inline void clear_sequence();
  static const int kSequenceFieldNumber = 1;
  inline ::google::protobuf::uint32 sequence() const;
  inline void set_sequence(::google::protobuf::uint32 value);

  // required .internal.QueryDBAgentReq.DatabaseType dbtype = 2;
  inline bool has_dbtype() const;
  inline void clear_dbtype();
  static const int kDbtypeFieldNumber = 2;
  inline ::internal::QueryDBAgentReq_DatabaseType dbtype() const;
  inline void set_dbtype(::internal::QueryDBAgentReq_DatabaseType value);

  // required .internal.QueryDBAgentReq.ActoinType action = 3;
  inline bool has_action() const;
  inline void clear_action();
  static const int kActionFieldNumber = 3;
  inline ::internal::QueryDBAgentReq_ActoinType action() const;
  inline void set_action(::internal::QueryDBAgentReq_ActoinType value);

  // required string dbname = 4;
  inline bool has_dbname() const;
  inline void clear_dbname();
  static const int kDbnameFieldNumber = 4;
  inline const ::std::string& dbname() const;
  inline void set_dbname(const ::std::string& value);
  inline void set_dbname(const char* value);
  inline void set_dbname(const char* value, size_t size);
  inline ::std::string* mutable_dbname();
  inline ::std::string* release_dbname();
  inline void set_allocated_dbname(::std::string* dbname);

  // optional string statement = 5;
  inline bool has_statement() const;
  inline void clear_statement();
  static const int kStatementFieldNumber = 5;
  inline const ::std::string& statement() const;
  inline void set_statement(const ::std::string& value);
  inline void set_statement(const char* value);
  inline void set_statement(const char* value, size_t size);
  inline ::std::string* mutable_statement();
  inline ::std::string* release_statement();
  inline void set_allocated_statement(::std::string* statement);

  // @@protoc_insertion_point(class_scope:internal.QueryDBAgentReq)
 private:
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_dbtype();
  inline void clear_has_dbtype();
  inline void set_has_action();
  inline void clear_has_action();
  inline void set_has_dbname();
  inline void clear_has_dbname();
  inline void set_has_statement();
  inline void clear_has_statement();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 sequence_;
  int dbtype_;
  ::std::string* dbname_;
  ::std::string* statement_;
  int action_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static QueryDBAgentReq* default_instance_;
};
// -------------------------------------------------------------------

class QueryDBAgentRsp : public ::google::protobuf::Message {
 public:
  QueryDBAgentRsp();
  virtual ~QueryDBAgentRsp();

  QueryDBAgentRsp(const QueryDBAgentRsp& from);

  inline QueryDBAgentRsp& operator=(const QueryDBAgentRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QueryDBAgentRsp& default_instance();

  void Swap(QueryDBAgentRsp* other);

  // implements Message ----------------------------------------------

  QueryDBAgentRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QueryDBAgentRsp& from);
  void MergeFrom(const QueryDBAgentRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 sequence = 1;
  inline bool has_sequence() const;
  inline void clear_sequence();
  static const int kSequenceFieldNumber = 1;
  inline ::google::protobuf::uint32 sequence() const;
  inline void set_sequence(::google::protobuf::uint32 value);

  // optional string result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline const ::std::string& result() const;
  inline void set_result(const ::std::string& value);
  inline void set_result(const char* value);
  inline void set_result(const char* value, size_t size);
  inline ::std::string* mutable_result();
  inline ::std::string* release_result();
  inline void set_allocated_result(::std::string* result);

  // @@protoc_insertion_point(class_scope:internal.QueryDBAgentRsp)
 private:
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* result_;
  ::google::protobuf::uint32 sequence_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static QueryDBAgentRsp* default_instance_;
};
// -------------------------------------------------------------------

class DBErrorRsp : public ::google::protobuf::Message {
 public:
  DBErrorRsp();
  virtual ~DBErrorRsp();

  DBErrorRsp(const DBErrorRsp& from);

  inline DBErrorRsp& operator=(const DBErrorRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBErrorRsp& default_instance();

  void Swap(DBErrorRsp* other);

  // implements Message ----------------------------------------------

  DBErrorRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DBErrorRsp& from);
  void MergeFrom(const DBErrorRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 sequence = 1;
  inline bool has_sequence() const;
  inline void clear_sequence();
  static const int kSequenceFieldNumber = 1;
  inline ::google::protobuf::uint32 sequence() const;
  inline void set_sequence(::google::protobuf::uint32 value);

  // required int32 error_code = 2;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 2;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);

  // optional string what = 3;
  inline bool has_what() const;
  inline void clear_what();
  static const int kWhatFieldNumber = 3;
  inline const ::std::string& what() const;
  inline void set_what(const ::std::string& value);
  inline void set_what(const char* value);
  inline void set_what(const char* value, size_t size);
  inline ::std::string* mutable_what();
  inline ::std::string* release_what();
  inline void set_allocated_what(::std::string* what);

  // @@protoc_insertion_point(class_scope:internal.DBErrorRsp)
 private:
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_what();
  inline void clear_has_what();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 sequence_;
  ::google::protobuf::int32 error_code_;
  ::std::string* what_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static DBErrorRsp* default_instance_;
};
// -------------------------------------------------------------------

class DBAgentErrorRsp : public ::google::protobuf::Message {
 public:
  DBAgentErrorRsp();
  virtual ~DBAgentErrorRsp();

  DBAgentErrorRsp(const DBAgentErrorRsp& from);

  inline DBAgentErrorRsp& operator=(const DBAgentErrorRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBAgentErrorRsp& default_instance();

  void Swap(DBAgentErrorRsp* other);

  // implements Message ----------------------------------------------

  DBAgentErrorRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DBAgentErrorRsp& from);
  void MergeFrom(const DBAgentErrorRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .internal.ErrorCode error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::internal::ErrorCode error_code() const;
  inline void set_error_code(::internal::ErrorCode value);

  // optional uint32 sequence = 2;
  inline bool has_sequence() const;
  inline void clear_sequence();
  static const int kSequenceFieldNumber = 2;
  inline ::google::protobuf::uint32 sequence() const;
  inline void set_sequence(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:internal.DBAgentErrorRsp)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_sequence();
  inline void clear_has_sequence();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int error_code_;
  ::google::protobuf::uint32 sequence_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static DBAgentErrorRsp* default_instance_;
};
// -------------------------------------------------------------------

class RouterErrorRsp : public ::google::protobuf::Message {
 public:
  RouterErrorRsp();
  virtual ~RouterErrorRsp();

  RouterErrorRsp(const RouterErrorRsp& from);

  inline RouterErrorRsp& operator=(const RouterErrorRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RouterErrorRsp& default_instance();

  void Swap(RouterErrorRsp* other);

  // implements Message ----------------------------------------------

  RouterErrorRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RouterErrorRsp& from);
  void MergeFrom(const RouterErrorRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .internal.ErrorCode error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::internal::ErrorCode error_code() const;
  inline void set_error_code(::internal::ErrorCode value);

  // optional string what = 2;
  inline bool has_what() const;
  inline void clear_what();
  static const int kWhatFieldNumber = 2;
  inline const ::std::string& what() const;
  inline void set_what(const ::std::string& value);
  inline void set_what(const char* value);
  inline void set_what(const char* value, size_t size);
  inline ::std::string* mutable_what();
  inline ::std::string* release_what();
  inline void set_allocated_what(::std::string* what);

  // @@protoc_insertion_point(class_scope:internal.RouterErrorRsp)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_what();
  inline void clear_has_what();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* what_;
  int error_code_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static RouterErrorRsp* default_instance_;
};
// -------------------------------------------------------------------

class LoginRouterReq : public ::google::protobuf::Message {
 public:
  LoginRouterReq();
  virtual ~LoginRouterReq();

  LoginRouterReq(const LoginRouterReq& from);

  inline LoginRouterReq& operator=(const LoginRouterReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRouterReq& default_instance();

  void Swap(LoginRouterReq* other);

  // implements Message ----------------------------------------------

  LoginRouterReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRouterReq& from);
  void MergeFrom(const LoginRouterReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .internal.NodeType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::internal::NodeType type() const;
  inline void set_type(::internal::NodeType value);

  // optional uint32 child_id = 2 [default = 1];
  inline bool has_child_id() const;
  inline void clear_child_id();
  static const int kChildIdFieldNumber = 2;
  inline ::google::protobuf::uint32 child_id() const;
  inline void set_child_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:internal.LoginRouterReq)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_child_id();
  inline void clear_has_child_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  ::google::protobuf::uint32 child_id_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static LoginRouterReq* default_instance_;
};
// -------------------------------------------------------------------

class LoginRouterRsp : public ::google::protobuf::Message {
 public:
  LoginRouterRsp();
  virtual ~LoginRouterRsp();

  LoginRouterRsp(const LoginRouterRsp& from);

  inline LoginRouterRsp& operator=(const LoginRouterRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRouterRsp& default_instance();

  void Swap(LoginRouterRsp* other);

  // implements Message ----------------------------------------------

  LoginRouterRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRouterRsp& from);
  void MergeFrom(const LoginRouterRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 heartbeat_interval = 1;
  inline bool has_heartbeat_interval() const;
  inline void clear_heartbeat_interval();
  static const int kHeartbeatIntervalFieldNumber = 1;
  inline ::google::protobuf::uint32 heartbeat_interval() const;
  inline void set_heartbeat_interval(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:internal.LoginRouterRsp)
 private:
  inline void set_has_heartbeat_interval();
  inline void clear_has_heartbeat_interval();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 heartbeat_interval_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static LoginRouterRsp* default_instance_;
};
// -------------------------------------------------------------------

class ForwardMessageReq : public ::google::protobuf::Message {
 public:
  ForwardMessageReq();
  virtual ~ForwardMessageReq();

  ForwardMessageReq(const ForwardMessageReq& from);

  inline ForwardMessageReq& operator=(const ForwardMessageReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ForwardMessageReq& default_instance();

  void Swap(ForwardMessageReq* other);

  // implements Message ----------------------------------------------

  ForwardMessageReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ForwardMessageReq& from);
  void MergeFrom(const ForwardMessageReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .internal.NodeType dst_type = 1;
  inline bool has_dst_type() const;
  inline void clear_dst_type();
  static const int kDstTypeFieldNumber = 1;
  inline ::internal::NodeType dst_type() const;
  inline void set_dst_type(::internal::NodeType value);

  // optional uint32 dst_child_id = 2 [default = 1];
  inline bool has_dst_child_id() const;
  inline void clear_dst_child_id();
  static const int kDstChildIdFieldNumber = 2;
  inline ::google::protobuf::uint32 dst_child_id() const;
  inline void set_dst_child_id(::google::protobuf::uint32 value);

  // required uint32 message_length = 3;
  inline bool has_message_length() const;
  inline void clear_message_length();
  static const int kMessageLengthFieldNumber = 3;
  inline ::google::protobuf::uint32 message_length() const;
  inline void set_message_length(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:internal.ForwardMessageReq)
 private:
  inline void set_has_dst_type();
  inline void clear_has_dst_type();
  inline void set_has_dst_child_id();
  inline void clear_has_dst_child_id();
  inline void set_has_message_length();
  inline void clear_has_message_length();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int dst_type_;
  ::google::protobuf::uint32 dst_child_id_;
  ::google::protobuf::uint32 message_length_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static ForwardMessageReq* default_instance_;
};
// -------------------------------------------------------------------

class ForwardMessageRsp : public ::google::protobuf::Message {
 public:
  ForwardMessageRsp();
  virtual ~ForwardMessageRsp();

  ForwardMessageRsp(const ForwardMessageRsp& from);

  inline ForwardMessageRsp& operator=(const ForwardMessageRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ForwardMessageRsp& default_instance();

  void Swap(ForwardMessageRsp* other);

  // implements Message ----------------------------------------------

  ForwardMessageRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ForwardMessageRsp& from);
  void MergeFrom(const ForwardMessageRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .internal.NodeType src_type = 1;
  inline bool has_src_type() const;
  inline void clear_src_type();
  static const int kSrcTypeFieldNumber = 1;
  inline ::internal::NodeType src_type() const;
  inline void set_src_type(::internal::NodeType value);

  // optional uint32 src_child_id = 2 [default = 1];
  inline bool has_src_child_id() const;
  inline void clear_src_child_id();
  static const int kSrcChildIdFieldNumber = 2;
  inline ::google::protobuf::uint32 src_child_id() const;
  inline void set_src_child_id(::google::protobuf::uint32 value);

  // required uint32 message_length = 3;
  inline bool has_message_length() const;
  inline void clear_message_length();
  static const int kMessageLengthFieldNumber = 3;
  inline ::google::protobuf::uint32 message_length() const;
  inline void set_message_length(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:internal.ForwardMessageRsp)
 private:
  inline void set_has_src_type();
  inline void clear_has_src_type();
  inline void set_has_src_child_id();
  inline void clear_has_src_child_id();
  inline void set_has_message_length();
  inline void clear_has_message_length();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int src_type_;
  ::google::protobuf::uint32 src_child_id_;
  ::google::protobuf::uint32 message_length_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static ForwardMessageRsp* default_instance_;
};
// -------------------------------------------------------------------

class BroadcastMessageReq : public ::google::protobuf::Message {
 public:
  BroadcastMessageReq();
  virtual ~BroadcastMessageReq();

  BroadcastMessageReq(const BroadcastMessageReq& from);

  inline BroadcastMessageReq& operator=(const BroadcastMessageReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BroadcastMessageReq& default_instance();

  void Swap(BroadcastMessageReq* other);

  // implements Message ----------------------------------------------

  BroadcastMessageReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BroadcastMessageReq& from);
  void MergeFrom(const BroadcastMessageReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .internal.NodeType dst_lists = 1;
  inline int dst_lists_size() const;
  inline void clear_dst_lists();
  static const int kDstListsFieldNumber = 1;
  inline ::internal::NodeType dst_lists(int index) const;
  inline void set_dst_lists(int index, ::internal::NodeType value);
  inline void add_dst_lists(::internal::NodeType value);
  inline const ::google::protobuf::RepeatedField<int>& dst_lists() const;
  inline ::google::protobuf::RepeatedField<int>* mutable_dst_lists();

  // required uint32 message_length = 3;
  inline bool has_message_length() const;
  inline void clear_message_length();
  static const int kMessageLengthFieldNumber = 3;
  inline ::google::protobuf::uint32 message_length() const;
  inline void set_message_length(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:internal.BroadcastMessageReq)
 private:
  inline void set_has_message_length();
  inline void clear_has_message_length();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField<int> dst_lists_;
  ::google::protobuf::uint32 message_length_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static BroadcastMessageReq* default_instance_;
};
// -------------------------------------------------------------------

class BroadcastMessageRsp : public ::google::protobuf::Message {
 public:
  BroadcastMessageRsp();
  virtual ~BroadcastMessageRsp();

  BroadcastMessageRsp(const BroadcastMessageRsp& from);

  inline BroadcastMessageRsp& operator=(const BroadcastMessageRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BroadcastMessageRsp& default_instance();

  void Swap(BroadcastMessageRsp* other);

  // implements Message ----------------------------------------------

  BroadcastMessageRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BroadcastMessageRsp& from);
  void MergeFrom(const BroadcastMessageRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .internal.NodeType src_type = 1;
  inline bool has_src_type() const;
  inline void clear_src_type();
  static const int kSrcTypeFieldNumber = 1;
  inline ::internal::NodeType src_type() const;
  inline void set_src_type(::internal::NodeType value);

  // optional uint32 src_child_id = 2 [default = 1];
  inline bool has_src_child_id() const;
  inline void clear_src_child_id();
  static const int kSrcChildIdFieldNumber = 2;
  inline ::google::protobuf::uint32 src_child_id() const;
  inline void set_src_child_id(::google::protobuf::uint32 value);

  // required uint32 message_length = 3;
  inline bool has_message_length() const;
  inline void clear_message_length();
  static const int kMessageLengthFieldNumber = 3;
  inline ::google::protobuf::uint32 message_length() const;
  inline void set_message_length(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:internal.BroadcastMessageRsp)
 private:
  inline void set_has_src_type();
  inline void clear_has_src_type();
  inline void set_has_src_child_id();
  inline void clear_has_src_child_id();
  inline void set_has_message_length();
  inline void clear_has_message_length();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int src_type_;
  ::google::protobuf::uint32 src_child_id_;
  ::google::protobuf::uint32 message_length_;
  friend void  protobuf_AddDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_AssignDesc_proto_2finternal_2eprotocol_2eproto();
  friend void protobuf_ShutdownFile_proto_2finternal_2eprotocol_2eproto();

  void InitAsDefaultInstance();
  static BroadcastMessageRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// PingReq

// -------------------------------------------------------------------

// PongRsp

// -------------------------------------------------------------------

// LoginDBAgentReq

// -------------------------------------------------------------------

// LoginDBAgentRsp

// required uint32 heartbeat_interval = 1;
inline bool LoginDBAgentRsp::has_heartbeat_interval() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginDBAgentRsp::set_has_heartbeat_interval() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginDBAgentRsp::clear_has_heartbeat_interval() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginDBAgentRsp::clear_heartbeat_interval() {
  heartbeat_interval_ = 0u;
  clear_has_heartbeat_interval();
}
inline ::google::protobuf::uint32 LoginDBAgentRsp::heartbeat_interval() const {
  // @@protoc_insertion_point(field_get:internal.LoginDBAgentRsp.heartbeat_interval)
  return heartbeat_interval_;
}
inline void LoginDBAgentRsp::set_heartbeat_interval(::google::protobuf::uint32 value) {
  set_has_heartbeat_interval();
  heartbeat_interval_ = value;
  // @@protoc_insertion_point(field_set:internal.LoginDBAgentRsp.heartbeat_interval)
}

// -------------------------------------------------------------------

// QueryDBAgentReq

// required uint32 sequence = 1;
inline bool QueryDBAgentReq::has_sequence() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QueryDBAgentReq::set_has_sequence() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QueryDBAgentReq::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QueryDBAgentReq::clear_sequence() {
  sequence_ = 0u;
  clear_has_sequence();
}
inline ::google::protobuf::uint32 QueryDBAgentReq::sequence() const {
  // @@protoc_insertion_point(field_get:internal.QueryDBAgentReq.sequence)
  return sequence_;
}
inline void QueryDBAgentReq::set_sequence(::google::protobuf::uint32 value) {
  set_has_sequence();
  sequence_ = value;
  // @@protoc_insertion_point(field_set:internal.QueryDBAgentReq.sequence)
}

// required .internal.QueryDBAgentReq.DatabaseType dbtype = 2;
inline bool QueryDBAgentReq::has_dbtype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void QueryDBAgentReq::set_has_dbtype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void QueryDBAgentReq::clear_has_dbtype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void QueryDBAgentReq::clear_dbtype() {
  dbtype_ = 1;
  clear_has_dbtype();
}
inline ::internal::QueryDBAgentReq_DatabaseType QueryDBAgentReq::dbtype() const {
  // @@protoc_insertion_point(field_get:internal.QueryDBAgentReq.dbtype)
  return static_cast< ::internal::QueryDBAgentReq_DatabaseType >(dbtype_);
}
inline void QueryDBAgentReq::set_dbtype(::internal::QueryDBAgentReq_DatabaseType value) {
  assert(::internal::QueryDBAgentReq_DatabaseType_IsValid(value));
  set_has_dbtype();
  dbtype_ = value;
  // @@protoc_insertion_point(field_set:internal.QueryDBAgentReq.dbtype)
}

// required .internal.QueryDBAgentReq.ActoinType action = 3;
inline bool QueryDBAgentReq::has_action() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void QueryDBAgentReq::set_has_action() {
  _has_bits_[0] |= 0x00000004u;
}
inline void QueryDBAgentReq::clear_has_action() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void QueryDBAgentReq::clear_action() {
  action_ = 1;
  clear_has_action();
}
inline ::internal::QueryDBAgentReq_ActoinType QueryDBAgentReq::action() const {
  // @@protoc_insertion_point(field_get:internal.QueryDBAgentReq.action)
  return static_cast< ::internal::QueryDBAgentReq_ActoinType >(action_);
}
inline void QueryDBAgentReq::set_action(::internal::QueryDBAgentReq_ActoinType value) {
  assert(::internal::QueryDBAgentReq_ActoinType_IsValid(value));
  set_has_action();
  action_ = value;
  // @@protoc_insertion_point(field_set:internal.QueryDBAgentReq.action)
}

// required string dbname = 4;
inline bool QueryDBAgentReq::has_dbname() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void QueryDBAgentReq::set_has_dbname() {
  _has_bits_[0] |= 0x00000008u;
}
inline void QueryDBAgentReq::clear_has_dbname() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void QueryDBAgentReq::clear_dbname() {
  if (dbname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    dbname_->clear();
  }
  clear_has_dbname();
}
inline const ::std::string& QueryDBAgentReq::dbname() const {
  // @@protoc_insertion_point(field_get:internal.QueryDBAgentReq.dbname)
  return *dbname_;
}
inline void QueryDBAgentReq::set_dbname(const ::std::string& value) {
  set_has_dbname();
  if (dbname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    dbname_ = new ::std::string;
  }
  dbname_->assign(value);
  // @@protoc_insertion_point(field_set:internal.QueryDBAgentReq.dbname)
}
inline void QueryDBAgentReq::set_dbname(const char* value) {
  set_has_dbname();
  if (dbname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    dbname_ = new ::std::string;
  }
  dbname_->assign(value);
  // @@protoc_insertion_point(field_set_char:internal.QueryDBAgentReq.dbname)
}
inline void QueryDBAgentReq::set_dbname(const char* value, size_t size) {
  set_has_dbname();
  if (dbname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    dbname_ = new ::std::string;
  }
  dbname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:internal.QueryDBAgentReq.dbname)
}
inline ::std::string* QueryDBAgentReq::mutable_dbname() {
  set_has_dbname();
  if (dbname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    dbname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:internal.QueryDBAgentReq.dbname)
  return dbname_;
}
inline ::std::string* QueryDBAgentReq::release_dbname() {
  clear_has_dbname();
  if (dbname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = dbname_;
    dbname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void QueryDBAgentReq::set_allocated_dbname(::std::string* dbname) {
  if (dbname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete dbname_;
  }
  if (dbname) {
    set_has_dbname();
    dbname_ = dbname;
  } else {
    clear_has_dbname();
    dbname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:internal.QueryDBAgentReq.dbname)
}

// optional string statement = 5;
inline bool QueryDBAgentReq::has_statement() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void QueryDBAgentReq::set_has_statement() {
  _has_bits_[0] |= 0x00000010u;
}
inline void QueryDBAgentReq::clear_has_statement() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void QueryDBAgentReq::clear_statement() {
  if (statement_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statement_->clear();
  }
  clear_has_statement();
}
inline const ::std::string& QueryDBAgentReq::statement() const {
  // @@protoc_insertion_point(field_get:internal.QueryDBAgentReq.statement)
  return *statement_;
}
inline void QueryDBAgentReq::set_statement(const ::std::string& value) {
  set_has_statement();
  if (statement_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statement_ = new ::std::string;
  }
  statement_->assign(value);
  // @@protoc_insertion_point(field_set:internal.QueryDBAgentReq.statement)
}
inline void QueryDBAgentReq::set_statement(const char* value) {
  set_has_statement();
  if (statement_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statement_ = new ::std::string;
  }
  statement_->assign(value);
  // @@protoc_insertion_point(field_set_char:internal.QueryDBAgentReq.statement)
}
inline void QueryDBAgentReq::set_statement(const char* value, size_t size) {
  set_has_statement();
  if (statement_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statement_ = new ::std::string;
  }
  statement_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:internal.QueryDBAgentReq.statement)
}
inline ::std::string* QueryDBAgentReq::mutable_statement() {
  set_has_statement();
  if (statement_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statement_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:internal.QueryDBAgentReq.statement)
  return statement_;
}
inline ::std::string* QueryDBAgentReq::release_statement() {
  clear_has_statement();
  if (statement_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = statement_;
    statement_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void QueryDBAgentReq::set_allocated_statement(::std::string* statement) {
  if (statement_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete statement_;
  }
  if (statement) {
    set_has_statement();
    statement_ = statement;
  } else {
    clear_has_statement();
    statement_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:internal.QueryDBAgentReq.statement)
}

// -------------------------------------------------------------------

// QueryDBAgentRsp

// required uint32 sequence = 1;
inline bool QueryDBAgentRsp::has_sequence() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QueryDBAgentRsp::set_has_sequence() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QueryDBAgentRsp::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QueryDBAgentRsp::clear_sequence() {
  sequence_ = 0u;
  clear_has_sequence();
}
inline ::google::protobuf::uint32 QueryDBAgentRsp::sequence() const {
  // @@protoc_insertion_point(field_get:internal.QueryDBAgentRsp.sequence)
  return sequence_;
}
inline void QueryDBAgentRsp::set_sequence(::google::protobuf::uint32 value) {
  set_has_sequence();
  sequence_ = value;
  // @@protoc_insertion_point(field_set:internal.QueryDBAgentRsp.sequence)
}

// optional string result = 2;
inline bool QueryDBAgentRsp::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void QueryDBAgentRsp::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void QueryDBAgentRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void QueryDBAgentRsp::clear_result() {
  if (result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_->clear();
  }
  clear_has_result();
}
inline const ::std::string& QueryDBAgentRsp::result() const {
  // @@protoc_insertion_point(field_get:internal.QueryDBAgentRsp.result)
  return *result_;
}
inline void QueryDBAgentRsp::set_result(const ::std::string& value) {
  set_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_ = new ::std::string;
  }
  result_->assign(value);
  // @@protoc_insertion_point(field_set:internal.QueryDBAgentRsp.result)
}
inline void QueryDBAgentRsp::set_result(const char* value) {
  set_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_ = new ::std::string;
  }
  result_->assign(value);
  // @@protoc_insertion_point(field_set_char:internal.QueryDBAgentRsp.result)
}
inline void QueryDBAgentRsp::set_result(const char* value, size_t size) {
  set_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_ = new ::std::string;
  }
  result_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:internal.QueryDBAgentRsp.result)
}
inline ::std::string* QueryDBAgentRsp::mutable_result() {
  set_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:internal.QueryDBAgentRsp.result)
  return result_;
}
inline ::std::string* QueryDBAgentRsp::release_result() {
  clear_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = result_;
    result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void QueryDBAgentRsp::set_allocated_result(::std::string* result) {
  if (result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete result_;
  }
  if (result) {
    set_has_result();
    result_ = result;
  } else {
    clear_has_result();
    result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:internal.QueryDBAgentRsp.result)
}

// -------------------------------------------------------------------

// DBErrorRsp

// required uint32 sequence = 1;
inline bool DBErrorRsp::has_sequence() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DBErrorRsp::set_has_sequence() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DBErrorRsp::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DBErrorRsp::clear_sequence() {
  sequence_ = 0u;
  clear_has_sequence();
}
inline ::google::protobuf::uint32 DBErrorRsp::sequence() const {
  // @@protoc_insertion_point(field_get:internal.DBErrorRsp.sequence)
  return sequence_;
}
inline void DBErrorRsp::set_sequence(::google::protobuf::uint32 value) {
  set_has_sequence();
  sequence_ = value;
  // @@protoc_insertion_point(field_set:internal.DBErrorRsp.sequence)
}

// required int32 error_code = 2;
inline bool DBErrorRsp::has_error_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DBErrorRsp::set_has_error_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DBErrorRsp::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DBErrorRsp::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 DBErrorRsp::error_code() const {
  // @@protoc_insertion_point(field_get:internal.DBErrorRsp.error_code)
  return error_code_;
}
inline void DBErrorRsp::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
  // @@protoc_insertion_point(field_set:internal.DBErrorRsp.error_code)
}

// optional string what = 3;
inline bool DBErrorRsp::has_what() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DBErrorRsp::set_has_what() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DBErrorRsp::clear_has_what() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DBErrorRsp::clear_what() {
  if (what_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_->clear();
  }
  clear_has_what();
}
inline const ::std::string& DBErrorRsp::what() const {
  // @@protoc_insertion_point(field_get:internal.DBErrorRsp.what)
  return *what_;
}
inline void DBErrorRsp::set_what(const ::std::string& value) {
  set_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_ = new ::std::string;
  }
  what_->assign(value);
  // @@protoc_insertion_point(field_set:internal.DBErrorRsp.what)
}
inline void DBErrorRsp::set_what(const char* value) {
  set_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_ = new ::std::string;
  }
  what_->assign(value);
  // @@protoc_insertion_point(field_set_char:internal.DBErrorRsp.what)
}
inline void DBErrorRsp::set_what(const char* value, size_t size) {
  set_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_ = new ::std::string;
  }
  what_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:internal.DBErrorRsp.what)
}
inline ::std::string* DBErrorRsp::mutable_what() {
  set_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:internal.DBErrorRsp.what)
  return what_;
}
inline ::std::string* DBErrorRsp::release_what() {
  clear_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = what_;
    what_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DBErrorRsp::set_allocated_what(::std::string* what) {
  if (what_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete what_;
  }
  if (what) {
    set_has_what();
    what_ = what;
  } else {
    clear_has_what();
    what_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:internal.DBErrorRsp.what)
}

// -------------------------------------------------------------------

// DBAgentErrorRsp

// required .internal.ErrorCode error_code = 1;
inline bool DBAgentErrorRsp::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DBAgentErrorRsp::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DBAgentErrorRsp::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DBAgentErrorRsp::clear_error_code() {
  error_code_ = 1;
  clear_has_error_code();
}
inline ::internal::ErrorCode DBAgentErrorRsp::error_code() const {
  // @@protoc_insertion_point(field_get:internal.DBAgentErrorRsp.error_code)
  return static_cast< ::internal::ErrorCode >(error_code_);
}
inline void DBAgentErrorRsp::set_error_code(::internal::ErrorCode value) {
  assert(::internal::ErrorCode_IsValid(value));
  set_has_error_code();
  error_code_ = value;
  // @@protoc_insertion_point(field_set:internal.DBAgentErrorRsp.error_code)
}

// optional uint32 sequence = 2;
inline bool DBAgentErrorRsp::has_sequence() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DBAgentErrorRsp::set_has_sequence() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DBAgentErrorRsp::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DBAgentErrorRsp::clear_sequence() {
  sequence_ = 0u;
  clear_has_sequence();
}
inline ::google::protobuf::uint32 DBAgentErrorRsp::sequence() const {
  // @@protoc_insertion_point(field_get:internal.DBAgentErrorRsp.sequence)
  return sequence_;
}
inline void DBAgentErrorRsp::set_sequence(::google::protobuf::uint32 value) {
  set_has_sequence();
  sequence_ = value;
  // @@protoc_insertion_point(field_set:internal.DBAgentErrorRsp.sequence)
}

// -------------------------------------------------------------------

// RouterErrorRsp

// required .internal.ErrorCode error_code = 1;
inline bool RouterErrorRsp::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RouterErrorRsp::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RouterErrorRsp::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RouterErrorRsp::clear_error_code() {
  error_code_ = 1;
  clear_has_error_code();
}
inline ::internal::ErrorCode RouterErrorRsp::error_code() const {
  // @@protoc_insertion_point(field_get:internal.RouterErrorRsp.error_code)
  return static_cast< ::internal::ErrorCode >(error_code_);
}
inline void RouterErrorRsp::set_error_code(::internal::ErrorCode value) {
  assert(::internal::ErrorCode_IsValid(value));
  set_has_error_code();
  error_code_ = value;
  // @@protoc_insertion_point(field_set:internal.RouterErrorRsp.error_code)
}

// optional string what = 2;
inline bool RouterErrorRsp::has_what() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RouterErrorRsp::set_has_what() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RouterErrorRsp::clear_has_what() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RouterErrorRsp::clear_what() {
  if (what_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_->clear();
  }
  clear_has_what();
}
inline const ::std::string& RouterErrorRsp::what() const {
  // @@protoc_insertion_point(field_get:internal.RouterErrorRsp.what)
  return *what_;
}
inline void RouterErrorRsp::set_what(const ::std::string& value) {
  set_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_ = new ::std::string;
  }
  what_->assign(value);
  // @@protoc_insertion_point(field_set:internal.RouterErrorRsp.what)
}
inline void RouterErrorRsp::set_what(const char* value) {
  set_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_ = new ::std::string;
  }
  what_->assign(value);
  // @@protoc_insertion_point(field_set_char:internal.RouterErrorRsp.what)
}
inline void RouterErrorRsp::set_what(const char* value, size_t size) {
  set_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_ = new ::std::string;
  }
  what_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:internal.RouterErrorRsp.what)
}
inline ::std::string* RouterErrorRsp::mutable_what() {
  set_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    what_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:internal.RouterErrorRsp.what)
  return what_;
}
inline ::std::string* RouterErrorRsp::release_what() {
  clear_has_what();
  if (what_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = what_;
    what_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RouterErrorRsp::set_allocated_what(::std::string* what) {
  if (what_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete what_;
  }
  if (what) {
    set_has_what();
    what_ = what;
  } else {
    clear_has_what();
    what_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:internal.RouterErrorRsp.what)
}

// -------------------------------------------------------------------

// LoginRouterReq

// required .internal.NodeType type = 1;
inline bool LoginRouterReq::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRouterReq::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRouterReq::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRouterReq::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::internal::NodeType LoginRouterReq::type() const {
  // @@protoc_insertion_point(field_get:internal.LoginRouterReq.type)
  return static_cast< ::internal::NodeType >(type_);
}
inline void LoginRouterReq::set_type(::internal::NodeType value) {
  assert(::internal::NodeType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:internal.LoginRouterReq.type)
}

// optional uint32 child_id = 2 [default = 1];
inline bool LoginRouterReq::has_child_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginRouterReq::set_has_child_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginRouterReq::clear_has_child_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginRouterReq::clear_child_id() {
  child_id_ = 1u;
  clear_has_child_id();
}
inline ::google::protobuf::uint32 LoginRouterReq::child_id() const {
  // @@protoc_insertion_point(field_get:internal.LoginRouterReq.child_id)
  return child_id_;
}
inline void LoginRouterReq::set_child_id(::google::protobuf::uint32 value) {
  set_has_child_id();
  child_id_ = value;
  // @@protoc_insertion_point(field_set:internal.LoginRouterReq.child_id)
}

// -------------------------------------------------------------------

// LoginRouterRsp

// required uint32 heartbeat_interval = 1;
inline bool LoginRouterRsp::has_heartbeat_interval() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRouterRsp::set_has_heartbeat_interval() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRouterRsp::clear_has_heartbeat_interval() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRouterRsp::clear_heartbeat_interval() {
  heartbeat_interval_ = 0u;
  clear_has_heartbeat_interval();
}
inline ::google::protobuf::uint32 LoginRouterRsp::heartbeat_interval() const {
  // @@protoc_insertion_point(field_get:internal.LoginRouterRsp.heartbeat_interval)
  return heartbeat_interval_;
}
inline void LoginRouterRsp::set_heartbeat_interval(::google::protobuf::uint32 value) {
  set_has_heartbeat_interval();
  heartbeat_interval_ = value;
  // @@protoc_insertion_point(field_set:internal.LoginRouterRsp.heartbeat_interval)
}

// -------------------------------------------------------------------

// ForwardMessageReq

// required .internal.NodeType dst_type = 1;
inline bool ForwardMessageReq::has_dst_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ForwardMessageReq::set_has_dst_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ForwardMessageReq::clear_has_dst_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ForwardMessageReq::clear_dst_type() {
  dst_type_ = 1;
  clear_has_dst_type();
}
inline ::internal::NodeType ForwardMessageReq::dst_type() const {
  // @@protoc_insertion_point(field_get:internal.ForwardMessageReq.dst_type)
  return static_cast< ::internal::NodeType >(dst_type_);
}
inline void ForwardMessageReq::set_dst_type(::internal::NodeType value) {
  assert(::internal::NodeType_IsValid(value));
  set_has_dst_type();
  dst_type_ = value;
  // @@protoc_insertion_point(field_set:internal.ForwardMessageReq.dst_type)
}

// optional uint32 dst_child_id = 2 [default = 1];
inline bool ForwardMessageReq::has_dst_child_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ForwardMessageReq::set_has_dst_child_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ForwardMessageReq::clear_has_dst_child_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ForwardMessageReq::clear_dst_child_id() {
  dst_child_id_ = 1u;
  clear_has_dst_child_id();
}
inline ::google::protobuf::uint32 ForwardMessageReq::dst_child_id() const {
  // @@protoc_insertion_point(field_get:internal.ForwardMessageReq.dst_child_id)
  return dst_child_id_;
}
inline void ForwardMessageReq::set_dst_child_id(::google::protobuf::uint32 value) {
  set_has_dst_child_id();
  dst_child_id_ = value;
  // @@protoc_insertion_point(field_set:internal.ForwardMessageReq.dst_child_id)
}

// required uint32 message_length = 3;
inline bool ForwardMessageReq::has_message_length() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ForwardMessageReq::set_has_message_length() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ForwardMessageReq::clear_has_message_length() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ForwardMessageReq::clear_message_length() {
  message_length_ = 0u;
  clear_has_message_length();
}
inline ::google::protobuf::uint32 ForwardMessageReq::message_length() const {
  // @@protoc_insertion_point(field_get:internal.ForwardMessageReq.message_length)
  return message_length_;
}
inline void ForwardMessageReq::set_message_length(::google::protobuf::uint32 value) {
  set_has_message_length();
  message_length_ = value;
  // @@protoc_insertion_point(field_set:internal.ForwardMessageReq.message_length)
}

// -------------------------------------------------------------------

// ForwardMessageRsp

// required .internal.NodeType src_type = 1;
inline bool ForwardMessageRsp::has_src_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ForwardMessageRsp::set_has_src_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ForwardMessageRsp::clear_has_src_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ForwardMessageRsp::clear_src_type() {
  src_type_ = 1;
  clear_has_src_type();
}
inline ::internal::NodeType ForwardMessageRsp::src_type() const {
  // @@protoc_insertion_point(field_get:internal.ForwardMessageRsp.src_type)
  return static_cast< ::internal::NodeType >(src_type_);
}
inline void ForwardMessageRsp::set_src_type(::internal::NodeType value) {
  assert(::internal::NodeType_IsValid(value));
  set_has_src_type();
  src_type_ = value;
  // @@protoc_insertion_point(field_set:internal.ForwardMessageRsp.src_type)
}

// optional uint32 src_child_id = 2 [default = 1];
inline bool ForwardMessageRsp::has_src_child_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ForwardMessageRsp::set_has_src_child_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ForwardMessageRsp::clear_has_src_child_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ForwardMessageRsp::clear_src_child_id() {
  src_child_id_ = 1u;
  clear_has_src_child_id();
}
inline ::google::protobuf::uint32 ForwardMessageRsp::src_child_id() const {
  // @@protoc_insertion_point(field_get:internal.ForwardMessageRsp.src_child_id)
  return src_child_id_;
}
inline void ForwardMessageRsp::set_src_child_id(::google::protobuf::uint32 value) {
  set_has_src_child_id();
  src_child_id_ = value;
  // @@protoc_insertion_point(field_set:internal.ForwardMessageRsp.src_child_id)
}

// required uint32 message_length = 3;
inline bool ForwardMessageRsp::has_message_length() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ForwardMessageRsp::set_has_message_length() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ForwardMessageRsp::clear_has_message_length() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ForwardMessageRsp::clear_message_length() {
  message_length_ = 0u;
  clear_has_message_length();
}
inline ::google::protobuf::uint32 ForwardMessageRsp::message_length() const {
  // @@protoc_insertion_point(field_get:internal.ForwardMessageRsp.message_length)
  return message_length_;
}
inline void ForwardMessageRsp::set_message_length(::google::protobuf::uint32 value) {
  set_has_message_length();
  message_length_ = value;
  // @@protoc_insertion_point(field_set:internal.ForwardMessageRsp.message_length)
}

// -------------------------------------------------------------------

// BroadcastMessageReq

// repeated .internal.NodeType dst_lists = 1;
inline int BroadcastMessageReq::dst_lists_size() const {
  return dst_lists_.size();
}
inline void BroadcastMessageReq::clear_dst_lists() {
  dst_lists_.Clear();
}
inline ::internal::NodeType BroadcastMessageReq::dst_lists(int index) const {
  // @@protoc_insertion_point(field_get:internal.BroadcastMessageReq.dst_lists)
  return static_cast< ::internal::NodeType >(dst_lists_.Get(index));
}
inline void BroadcastMessageReq::set_dst_lists(int index, ::internal::NodeType value) {
  assert(::internal::NodeType_IsValid(value));
  dst_lists_.Set(index, value);
  // @@protoc_insertion_point(field_set:internal.BroadcastMessageReq.dst_lists)
}
inline void BroadcastMessageReq::add_dst_lists(::internal::NodeType value) {
  assert(::internal::NodeType_IsValid(value));
  dst_lists_.Add(value);
  // @@protoc_insertion_point(field_add:internal.BroadcastMessageReq.dst_lists)
}
inline const ::google::protobuf::RepeatedField<int>&
BroadcastMessageReq::dst_lists() const {
  // @@protoc_insertion_point(field_list:internal.BroadcastMessageReq.dst_lists)
  return dst_lists_;
}
inline ::google::protobuf::RepeatedField<int>*
BroadcastMessageReq::mutable_dst_lists() {
  // @@protoc_insertion_point(field_mutable_list:internal.BroadcastMessageReq.dst_lists)
  return &dst_lists_;
}

// required uint32 message_length = 3;
inline bool BroadcastMessageReq::has_message_length() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BroadcastMessageReq::set_has_message_length() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BroadcastMessageReq::clear_has_message_length() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BroadcastMessageReq::clear_message_length() {
  message_length_ = 0u;
  clear_has_message_length();
}
inline ::google::protobuf::uint32 BroadcastMessageReq::message_length() const {
  // @@protoc_insertion_point(field_get:internal.BroadcastMessageReq.message_length)
  return message_length_;
}
inline void BroadcastMessageReq::set_message_length(::google::protobuf::uint32 value) {
  set_has_message_length();
  message_length_ = value;
  // @@protoc_insertion_point(field_set:internal.BroadcastMessageReq.message_length)
}

// -------------------------------------------------------------------

// BroadcastMessageRsp

// required .internal.NodeType src_type = 1;
inline bool BroadcastMessageRsp::has_src_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BroadcastMessageRsp::set_has_src_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BroadcastMessageRsp::clear_has_src_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BroadcastMessageRsp::clear_src_type() {
  src_type_ = 1;
  clear_has_src_type();
}
inline ::internal::NodeType BroadcastMessageRsp::src_type() const {
  // @@protoc_insertion_point(field_get:internal.BroadcastMessageRsp.src_type)
  return static_cast< ::internal::NodeType >(src_type_);
}
inline void BroadcastMessageRsp::set_src_type(::internal::NodeType value) {
  assert(::internal::NodeType_IsValid(value));
  set_has_src_type();
  src_type_ = value;
  // @@protoc_insertion_point(field_set:internal.BroadcastMessageRsp.src_type)
}

// optional uint32 src_child_id = 2 [default = 1];
inline bool BroadcastMessageRsp::has_src_child_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BroadcastMessageRsp::set_has_src_child_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BroadcastMessageRsp::clear_has_src_child_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BroadcastMessageRsp::clear_src_child_id() {
  src_child_id_ = 1u;
  clear_has_src_child_id();
}
inline ::google::protobuf::uint32 BroadcastMessageRsp::src_child_id() const {
  // @@protoc_insertion_point(field_get:internal.BroadcastMessageRsp.src_child_id)
  return src_child_id_;
}
inline void BroadcastMessageRsp::set_src_child_id(::google::protobuf::uint32 value) {
  set_has_src_child_id();
  src_child_id_ = value;
  // @@protoc_insertion_point(field_set:internal.BroadcastMessageRsp.src_child_id)
}

// required uint32 message_length = 3;
inline bool BroadcastMessageRsp::has_message_length() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BroadcastMessageRsp::set_has_message_length() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BroadcastMessageRsp::clear_has_message_length() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BroadcastMessageRsp::clear_message_length() {
  message_length_ = 0u;
  clear_has_message_length();
}
inline ::google::protobuf::uint32 BroadcastMessageRsp::message_length() const {
  // @@protoc_insertion_point(field_get:internal.BroadcastMessageRsp.message_length)
  return message_length_;
}
inline void BroadcastMessageRsp::set_message_length(::google::protobuf::uint32 value) {
  set_has_message_length();
  message_length_ = value;
  // @@protoc_insertion_point(field_set:internal.BroadcastMessageRsp.message_length)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace internal

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::internal::QueryDBAgentReq_ActoinType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::internal::QueryDBAgentReq_ActoinType>() {
  return ::internal::QueryDBAgentReq_ActoinType_descriptor();
}
template <> struct is_proto_enum< ::internal::QueryDBAgentReq_DatabaseType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::internal::QueryDBAgentReq_DatabaseType>() {
  return ::internal::QueryDBAgentReq_DatabaseType_descriptor();
}
template <> struct is_proto_enum< ::internal::ErrorCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::internal::ErrorCode>() {
  return ::internal::ErrorCode_descriptor();
}
template <> struct is_proto_enum< ::internal::NodeType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::internal::NodeType>() {
  return ::internal::NodeType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2finternal_2eprotocol_2eproto__INCLUDED
