// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/client_logic.proto

#ifndef PROTOBUF_proto_2fclient_5flogic_2eproto__INCLUDED
#define PROTOBUF_proto_2fclient_5flogic_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cli {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fclient_5flogic_2eproto();
void protobuf_AssignDesc_proto_2fclient_5flogic_2eproto();
void protobuf_ShutdownFile_proto_2fclient_5flogic_2eproto();

class UserEnterReq;
class UserEnterRsp;
class UserLeaveReq;

// ===================================================================

class UserEnterReq : public ::google::protobuf::Message {
 public:
  UserEnterReq();
  virtual ~UserEnterReq();

  UserEnterReq(const UserEnterReq& from);

  inline UserEnterReq& operator=(const UserEnterReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserEnterReq& default_instance();

  void Swap(UserEnterReq* other);

  // implements Message ----------------------------------------------

  UserEnterReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserEnterReq& from);
  void MergeFrom(const UserEnterReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:cli.UserEnterReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fclient_5flogic_2eproto();
  friend void protobuf_AssignDesc_proto_2fclient_5flogic_2eproto();
  friend void protobuf_ShutdownFile_proto_2fclient_5flogic_2eproto();

  void InitAsDefaultInstance();
  static UserEnterReq* default_instance_;
};
// -------------------------------------------------------------------

class UserEnterRsp : public ::google::protobuf::Message {
 public:
  UserEnterRsp();
  virtual ~UserEnterRsp();

  UserEnterRsp(const UserEnterRsp& from);

  inline UserEnterRsp& operator=(const UserEnterRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserEnterRsp& default_instance();

  void Swap(UserEnterRsp* other);

  // implements Message ----------------------------------------------

  UserEnterRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserEnterRsp& from);
  void MergeFrom(const UserEnterRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cli.UserEnterRsp)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 user_id_;
  friend void  protobuf_AddDesc_proto_2fclient_5flogic_2eproto();
  friend void protobuf_AssignDesc_proto_2fclient_5flogic_2eproto();
  friend void protobuf_ShutdownFile_proto_2fclient_5flogic_2eproto();

  void InitAsDefaultInstance();
  static UserEnterRsp* default_instance_;
};
// -------------------------------------------------------------------

class UserLeaveReq : public ::google::protobuf::Message {
 public:
  UserLeaveReq();
  virtual ~UserLeaveReq();

  UserLeaveReq(const UserLeaveReq& from);

  inline UserLeaveReq& operator=(const UserLeaveReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserLeaveReq& default_instance();

  void Swap(UserLeaveReq* other);

  // implements Message ----------------------------------------------

  UserLeaveReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserLeaveReq& from);
  void MergeFrom(const UserLeaveReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:cli.UserLeaveReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fclient_5flogic_2eproto();
  friend void protobuf_AssignDesc_proto_2fclient_5flogic_2eproto();
  friend void protobuf_ShutdownFile_proto_2fclient_5flogic_2eproto();

  void InitAsDefaultInstance();
  static UserLeaveReq* default_instance_;
};
// ===================================================================


// ===================================================================

// UserEnterReq

// -------------------------------------------------------------------

// UserEnterRsp

// required uint32 user_id = 1;
inline bool UserEnterRsp::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserEnterRsp::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserEnterRsp::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserEnterRsp::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 UserEnterRsp::user_id() const {
  // @@protoc_insertion_point(field_get:cli.UserEnterRsp.user_id)
  return user_id_;
}
inline void UserEnterRsp::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
  // @@protoc_insertion_point(field_set:cli.UserEnterRsp.user_id)
}

// -------------------------------------------------------------------

// UserLeaveReq


// @@protoc_insertion_point(namespace_scope)

}  // namespace cli

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fclient_5flogic_2eproto__INCLUDED
